# site settings
title: Ruby Michele Thompson
subtitle: Master of Business Administration & Master of Science in Data Science Candidate
email: RubyMicheleThompson@gmail.com
description: Portfolio of relevant project from MBA/MSDS Candidate Ruby Thompson.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ruby Thompson
street_address: 900 State St 
city: Salem
state: OR
zip_code: 97301
country: United States of America
phone: (503)812-1265

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  LinkedIn: https://www.linkedin.com/in/ruby-michele-thompson


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
